import type { Metadata } from "next";
import { Open_Sans, Fanwood_Text } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import Footer from "@/components/layout/Footer/Footer";

const openSans = Open_Sans({
  variable: "--font-family",
  subsets: ["latin"],
});

const fanwoodText = Fanwood_Text({
  weight: "400",
  variable: "--second-family",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pottery Studio",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${fanwoodText.variable}`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
